### ISSUE TITLE
Japanese version of website does not have grid elements 

### ISSUE THREAD

**Issue by kzngt** [aabxd/achievement-standard-91893-new#10]
# this is a bug

While the homepage (in English) has the grid elements with assorted colours. The Japanese version of the page does not produce this behaviour.

## Possible fixes
* It could be that the link to the stylesheet is done incorrectly; possibly pointing to an invalid reference?
* Elements from the previous page was not changed in Japanese version?

> It should be an easy fix :)

**Comment by aabxd** [comment]
Fixed.
