### ISSUE TITLE
Usability - Background colours in grid made text hard to read. Especially blue and purple sections.

### ISSUE THREAD

**Issue by mr-harding** [aabxd/achievement-standard-91893-new#12]
Consider changing colours to make text easier to read

**Comment by aabxd** [comment]
CSS grid has been updated with background images along with gradient overlays. As of now, the text is white and the overlays are the same with a bright colour. Obviously this didn't fix the issue regarding readable text but it should be resolved in a couple of minutes.

**Comment by aabxd** [comment]
Content in grid elements should be readable now. Will confirm with user testing & feedback
