### ISSUE TITLE
Uneven margins on responsive view (for example iPhone 6/7/8)

### ISSUE THREAD

**Issue by kzngt** [aabxd/achievement-standard-91893-new#8]
![image](https://user-images.githubusercontent.com/50852148/63977649-6c613e80-cb08-11e9-88cc-5e651cacea81.png)

The above image shows that when the website is put into responsive view, the left margin has less of a gap than the right margin.

Steps to reproduce (current version):
1. Use Chrome or any other supported browser with Inspect Element feature
2. Enable responsive view

**Comment by aabxd** [comment]
Resolved. should also display grid elements comfortably for mobile users
